# Rosé Pine Dawn colours for hyprlock
$lock_inner = rgba(faf4edcc)                       # base
$lock_outer = rgba(907aa9ee) rgba(56949fee) 45deg  # iris -> foam
$lock_check = rgba(56949fee) rgba(286983ee) 120deg # foam -> pine
$lock_fail  = rgba(b4637aee) rgba(d7827eee) 40deg  # love -> rose
$lock_font  = rgb(87, 82, 121)                     # text
$lock_time  = rgba(575279ee)                       # text
$lock_date  = rgba(907aa9ee)                       # iris
