-- Monitor configuration
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
--
-- NOTE: the old setup had TWO monitor files: the root monitors.conf
-- (autogenerated once by nwg-displays) and UserConfigs/Monitors.conf.
-- Only the latter was actually `source`d from hyprland.conf -- the root
-- one was dead weight. This file replaces UserConfigs/Monitors.conf only.

hl.monitor({ output = "eDP-1", mode = "1920x1200@90.0", position = "1920x0", scale = 1 })
hl.monitor({ output = "desc:Dell Inc. DELL P2319H 9K41KM3", mode = "1920x1080@60", position = "1920x1200", scale = 1 })
hl.monitor({ output = "desc:HP Inc. HP E24i G4 CNK2470DJB", mode = "1920x1200@59.950", position = "0x1080", scale = 1 })

-- Fallback for any other/unlisted monitor.
-- NOTE: the old line was `monitor = ,prefered, auto, 1` -- "prefered" is
-- misspelled (one r). Hyprland's magic keyword is "preferred"; the typo'd
-- version was very likely being parsed as a literal (bogus) mode string
-- rather than the "use the monitor's preferred mode" keyword, so this
-- catch-all rule may not have been working as intended. Fixed here.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- Laptop lid-switch handling: see keybinds_laptop.lua -- the old
-- Laptops.conf/LaptopDisplay.conf lid-switch trick is disabled by default
-- in this config too (it always was, it's commented out in the source).
