# Rosé Pine Moon colours for hyprlock
$lock_inner = rgba(232136cc)                       # base
$lock_outer = rgba(c4a7e7ee) rgba(9ccfd8ee) 45deg  # iris -> foam
$lock_check = rgba(9ccfd8ee) rgba(3e8fb0ee) 120deg # foam -> pine
$lock_fail  = rgba(eb6f92ee) rgba(b4637aee) 40deg  # love
$lock_font  = rgb(224, 222, 244)                   # text
$lock_time  = rgba(e0def4ee)                       # text
$lock_date  = rgba(c4a7e7ee)                       # iris
